// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KorisnikKlub", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("integer");

                    b.Property<int>("KlubId")
                        .HasColumnType("integer");

                    b.HasKey("KorisnikId", "KlubId");

                    b.HasIndex("KlubId");

                    b.ToTable("KorisnikKlub", (string)null);
                });

            modelBuilder.Entity("Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lozinka = "SigurnaSifra123!",
                            Username = "admin.super@domain.com"
                        });
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojGodina")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DatumKrajaUgovora")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DatumPocetkaUgovora")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KlubID")
                        .HasColumnType("integer");

                    b.Property<string>("ListaKlubova")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<float>("Tezina")
                        .HasColumnType("real");

                    b.Property<float>("Visina")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("KlubID");

                    b.ToTable("Igrac");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Istorija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prihodi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rashodi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sponzori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<string>("Trofeji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klub");
                });

            modelBuilder.Entity("Models.Kolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojKola")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KrajKola")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PocetakKola")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sezona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TakmicenjeId")
                        .HasColumnType("integer");

                    b.Property<int>("TipKola")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TakmicenjeId");

                    b.ToTable("Kolo");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Telefon")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Models.Novosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BrojDislajkova")
                        .HasColumnType("integer");

                    b.Property<int>("BrojLajkova")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KlubID")
                        .HasColumnType("integer");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sazetak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KlubID");

                    b.ToTable("Novosti");
                });

            modelBuilder.Entity("Models.Statistika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsistencijeDomacin")
                        .HasColumnType("integer");

                    b.Property<int?>("AsistencijeGost")
                        .HasColumnType("integer");

                    b.Property<string>("ListaStrelaca")
                        .HasColumnType("text");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<int>("TrenutniMinut")
                        .HasColumnType("integer");

                    b.Property<int>("UtakmicaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtakmicaId")
                        .IsUnique();

                    b.ToTable("Statistika");

                    b.HasDiscriminator<int>("Sport");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.Tabela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojBodova")
                        .HasColumnType("integer");

                    b.Property<int>("BrojDatihPoena")
                        .HasColumnType("integer");

                    b.Property<int>("BrojPrimljenihPoena")
                        .HasColumnType("integer");

                    b.Property<int>("Izgubljene")
                        .HasColumnType("integer");

                    b.Property<int>("KlubId")
                        .HasColumnType("integer");

                    b.Property<string>("NazivTabele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Neresene")
                        .HasColumnType("integer");

                    b.Property<int>("Odigrane")
                        .HasColumnType("integer");

                    b.Property<int>("Pobede")
                        .HasColumnType("integer");

                    b.Property<int>("Razlika")
                        .HasColumnType("integer");

                    b.Property<string>("Sezona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TakmicenjeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.HasIndex("TakmicenjeId");

                    b.ToTable("Tabela");
                });

            modelBuilder.Entity("Models.Takmicenje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Takmicenje");
                });

            modelBuilder.Entity("Models.Ucinak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Asistencije")
                        .HasColumnType("integer");

                    b.Property<int?>("BlokiraniUdarci")
                        .HasColumnType("integer");

                    b.Property<int?>("CrveniKartoni")
                        .HasColumnType("integer");

                    b.Property<int>("IgracId")
                        .HasColumnType("integer");

                    b.Property<int>("IndeksKorisnosti")
                        .HasColumnType("integer");

                    b.Property<int?>("Iskljucenja")
                        .HasColumnType("integer");

                    b.Property<int?>("IzgubljeneLopte")
                        .HasColumnType("integer");

                    b.Property<string>("NazivKluba")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OdigraneUtakmice")
                        .HasColumnType("integer");

                    b.Property<int>("Pogotci")
                        .HasColumnType("integer");

                    b.Property<int?>("PredjenaDistancaKM")
                        .HasColumnType("integer");

                    b.Property<string>("Sezona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Skokovi")
                        .HasColumnType("integer");

                    b.Property<int?>("SkokoviDF")
                        .HasColumnType("integer");

                    b.Property<int?>("SkokoviOF")
                        .HasColumnType("integer");

                    b.Property<int>("TakmicenjeId")
                        .HasColumnType("integer");

                    b.Property<int?>("UkradeneLopte")
                        .HasColumnType("integer");

                    b.Property<int?>("UkupnoDodavanja")
                        .HasColumnType("integer");

                    b.Property<int?>("UkupnoFaula")
                        .HasColumnType("integer");

                    b.Property<int>("UkupnoSuteva")
                        .HasColumnType("integer");

                    b.Property<int?>("UkupnoTacnihDodavanja")
                        .HasColumnType("integer");

                    b.Property<int?>("VraceniPosedi")
                        .HasColumnType("integer");

                    b.Property<int?>("ZutiKartoni")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IgracId");

                    b.HasIndex("TakmicenjeId");

                    b.ToTable("UcinakIgraca");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPocetkaUtakmice")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domacin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KoloId")
                        .HasColumnType("integer");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rezultat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StatistikaId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<bool>("Uzivo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KoloId");

                    b.ToTable("Utakmica");
                });

            modelBuilder.Entity("Models.FudbalStatistika", b =>
                {
                    b.HasBaseType("Models.Statistika");

                    b.Property<int>("CrveniKartoniDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("CrveniKartoniGost")
                        .HasColumnType("integer");

                    b.Property<int>("GoloviDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("GoloviGost")
                        .HasColumnType("integer");

                    b.Property<int>("PosedDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("PosedGost")
                        .HasColumnType("integer");

                    b.Property<int>("PreciznostPasovaDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("PreciznostPasovaGost")
                        .HasColumnType("integer");

                    b.Property<int>("SutDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("SutGost")
                        .HasColumnType("integer");

                    b.Property<int>("SutKaGolDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("SutKaGolGost")
                        .HasColumnType("integer");

                    b.Property<int>("ZutiKartoniDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("ZutiKartoniGost")
                        .HasColumnType("integer");

                    b.ToTable("Statistika");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Models.KosarkaStatistika", b =>
                {
                    b.HasBaseType("Models.Statistika");

                    b.Property<int>("BlocksDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("BlocksGost")
                        .HasColumnType("integer");

                    b.Property<int>("CetvCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("CetvCetGost")
                        .HasColumnType("integer");

                    b.Property<int>("DrugaCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("DrugaCetGost")
                        .HasColumnType("integer");

                    b.Property<int>("FreeThrowDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("FreeThrowGost")
                        .HasColumnType("integer");

                    b.Property<int>("PrvaCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("PrvaCetGost")
                        .HasColumnType("integer");

                    b.Property<int>("ReboundsDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("ReboundsGost")
                        .HasColumnType("integer");

                    b.Property<int>("StealsDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("StealsGost")
                        .HasColumnType("integer");

                    b.Property<int>("ThreePointDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("ThreePointGost")
                        .HasColumnType("integer");

                    b.Property<int>("TrecaCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("TrecaCetGost")
                        .HasColumnType("integer");

                    b.Property<int>("TwoPointDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("TwoPointGost")
                        .HasColumnType("integer");

                    b.ToTable("Statistika");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Models.VaterpoloStatistika", b =>
                {
                    b.HasBaseType("Models.Statistika");

                    b.Property<bool>("IgraniPeterci")
                        .HasColumnType("boolean");

                    b.Property<int>("IskljucenjaDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("IskljucenjaGost")
                        .HasColumnType("integer");

                    b.Property<int>("PeterciDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("PeterciGost")
                        .HasColumnType("integer");

                    b.Property<int>("VP_CetvCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("VP_CetvCetGost")
                        .HasColumnType("integer");

                    b.Property<int>("VP_DrugaCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("VP_DrugaCetGost")
                        .HasColumnType("integer");

                    b.Property<int>("VP_PrvaCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("VP_PrvaCetGost")
                        .HasColumnType("integer");

                    b.Property<int>("VP_TrecaCetDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("VP_TrecaCetGost")
                        .HasColumnType("integer");

                    b.ToTable("Statistika");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("KorisnikKlub", b =>
                {
                    b.HasOne("Models.Klub", null)
                        .WithMany()
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.HasOne("Models.Klub", "Klub")
                        .WithMany("Igraci")
                        .HasForeignKey("KlubID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Models.Kolo", b =>
                {
                    b.HasOne("Models.Takmicenje", "Takmicenje")
                        .WithMany("Kolа")
                        .HasForeignKey("TakmicenjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Takmicenje");
                });

            modelBuilder.Entity("Models.Novosti", b =>
                {
                    b.HasOne("Models.Klub", "Klub")
                        .WithMany("Novosti")
                        .HasForeignKey("KlubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Models.Statistika", b =>
                {
                    b.HasOne("Models.Utakmica", "Utakmica")
                        .WithOne("Statistika")
                        .HasForeignKey("Models.Statistika", "UtakmicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utakmica");
                });

            modelBuilder.Entity("Models.Tabela", b =>
                {
                    b.HasOne("Models.Klub", "Klub")
                        .WithMany("Takmicenja")
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Takmicenje", "Takmicenje")
                        .WithMany("Klubovi")
                        .HasForeignKey("TakmicenjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klub");

                    b.Navigation("Takmicenje");
                });

            modelBuilder.Entity("Models.Ucinak", b =>
                {
                    b.HasOne("Models.Igrac", "Igrac")
                        .WithMany("Ucinci")
                        .HasForeignKey("IgracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Takmicenje", "Takmicenje")
                        .WithMany("Ucinci")
                        .HasForeignKey("TakmicenjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igrac");

                    b.Navigation("Takmicenje");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.HasOne("Models.Kolo", "Kolo")
                        .WithMany("Utakmice")
                        .HasForeignKey("KoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kolo");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Navigation("Ucinci");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Navigation("Igraci");

                    b.Navigation("Novosti");

                    b.Navigation("Takmicenja");
                });

            modelBuilder.Entity("Models.Kolo", b =>
                {
                    b.Navigation("Utakmice");
                });

            modelBuilder.Entity("Models.Takmicenje", b =>
                {
                    b.Navigation("Klubovi");

                    b.Navigation("Kolа");

                    b.Navigation("Ucinci");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.Navigation("Statistika");
                });
#pragma warning restore 612, 618
        }
    }
}
